import arcade

SPRITE_SCALING = 2
PLAYER_SCALING = 2*0.85
SPRITE_NATIVE_SIZE = 30
STATUS_BAR_HEIGHT = 40
SPRITE_SIZE = SPRITE_NATIVE_SIZE * SPRITE_SCALING

SCREEN_WIDTH = 15*SPRITE_SIZE
GAME_HEIGHT = 10*SPRITE_SIZE
SCREEN_HEIGHT = GAME_HEIGHT + STATUS_BAR_HEIGHT

# How many pixels to keep as a minimum margin between the character
# and the edge of the screen.
VIEWPORT_MARGIN = 40
RIGHT_MARGIN = 150

# Hotkeys
WEAPON_SWAP_KEY = arcade.key.T

# Physics
MOVEMENT_SPEED = 2*2.5
JUMP_SPEED = 2*6
SECOND_JUMP_SPEED = 2*4.5
GRAVITY = 2*0.25

# These numbers represent "states" that the game can be in.
INSTRUCTIONS_PAGE = 0
GAME_RUNNING = 1
GAME_OVER = 2
PAUSE = 3


MENU_LENGTH = 3
